In [26]:
import pandas as pd 
df1=pd.read_csv("student-scores.csv")
df=df1.copy()
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [27]:
df.drop(columns=['id','first_name','last_name','email'],axis=1,inplace=True)

In [28]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [29]:
df['total_score']=df['math_score']+df['history_score']+df['physics_score']+df['chemistry_score']+df['biology_score']+df['geography_score']+df['english_score']
df['average_score']=df["total_score"]/7
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521,74.428571

In [30]:
len(df['career_aspiration'].unique())

17

In [31]:
gender_map={'male':0,'female':1}
part_time_job_map={False:0,True:1}
extracurricular_activities_map={False:0,True:1}
career_aspiration_map={
    'lawyer':0,'Doctor':1,'Government Officer':2,'Artist':3,'Environmental Activist':4,
    'Software Engineer':5,'Teacher':6,'Buisness Owner':7,'Scientist':8,
    'Banker':9,'Writer':10,'Accountant':11,'Designer':12,
    'Construction Engineer':13,'Game Developer':14,'Stock Investor':15,
    'Real Estate Developer':16
}

    #apply mapping To the Dataframe 
df['gender']=df['gender'].map(gender_map)
df['part_time_job']=df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities']=df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration']=df['career_aspiration'].map(career_aspiration_map)

In [32]:
df.shape

(2000, 15)

In [33]:
print(y.isna().sum())

0

In [34]:
df = df.dropna(subset=['career_aspiration'])
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

In [35]:
df['career_aspiration'] = df['career_aspiration'].fillna(df['career_aspiration'].mode())

In [36]:
from imblearn.over_sampling import SMOTE

smote=SMOTE(random_state=42)

X=df.drop('career_aspiration',axis=1)
y=df['career_aspiration']

X_resampled,y_resampled=smote.fit_resample(X,y)

In [37]:
y_resampled.shape

(4410,)

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_resampled,y_resampled,test_size=0.2,random_state=42)

In [39]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((3528, 14), (3528,), (882, 14), (882,))

In [40]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [41]:
X_train_scaled.shape

(3528, 14)

Models Training (Multiple Models )

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
# from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define Models 
models = {
    'Logistic Regression': LogisticRegression(),
    'Support Vector Classifier': SVC(),
    'Random Forest Classifier': RandomForestClassifier(),
    'K Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree Classifier': DecisionTreeClassifier(),
    'Gaussian Naive Bayes': GaussianNB(),
    'AdaBoost Classifier': AdaBoostClassifier(),
    'Gradient Boosting Classifier': GradientBoostingClassifier(),
    # 'XGBoost Classifier': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print Metrics
    print('Accuracy:', accuracy)
    print("Classification Report:\n", classification_rep)
    print('Confusion Matrix:\n', conf_matrix)

==================================================
Model: Logistic Regression
Accuracy: 0.5170068027210885
Classification Report:
               precision    recall  f1-score   support

         1.0       0.58      0.64      0.61        70
         2.0       0.60      0.41      0.49        70
         3.0       0.51      0.69      0.59        55
         5.0       0.39      0.46      0.42        57
         6.0       0.53      0.81      0.64        59
         8.0       0.60      0.53      0.57        73
         9.0       0.27      0.17      0.21        59
        10.0       0.58      0.75      0.66        61
        11.0       0.54      0.53      0.53        57
        12.0       0.33      0.23      0.27        65
        13.0       0.46      0.60      0.52        70
        14.0       0.80      0.85      0.82        60
        15.0       0.33      0.17      0.23        70
        16.0       0.49      0.45      0.47        56

    accuracy                           0.52       882
   macro avg       0.50      0.52      0.50       882
weighted avg       0.50      0.52      0.50       882

Confusion Matrix:
 [[45  0  0  6  0  7  2  2  0  0  7  0  1  0]
 [ 0 29  6  0 16  0  0  2  0  8  2  1  0  6]
 [ 0  3 38  0  2  0  0  0  0  0  0  3  0  9]
 [ 3  0  0 26  1  0  8  2  1  2 12  0  2  0]
 [ 0  0  0  2 48  0  1  2  2  3  0  0  0  1]
 [21  0  0  2  0 39  0  9  1  0  0  0  1  0]
 [ 0  3  0 11  7  6 10  4  6  2  9  0  1  0]
 [ 1  0  0  0  2  1  5 46  1  1  4  0  0  0]
 [ 3  0  0  1  0  0  5  1 30  2  8  0  7  0]
 [ 0  4  5  4  7  8  0  4  2 15  1  3  7  5]
 [ 2  1  0  5  0  4  1  4  3  3 42  0  5  0]
 [ 0  0  8  0  0  0  0  0  0  0  0 51  0  1]
 [ 3  6  0  9  2  0  5  3 10  8  7  1 12  4]
 [ 0  2 17  1  5  0  0  0  0  1  0  5  0 25]]
==================================================
Model: Support Vector Classifier
Accuracy: 0.6757369614512472
Classification Report:
               precision    recall  f1-score   support

         1.0       0.69      0.71      0.70        70
         2.0       0.80      0.69      0.74        70
         3.0       0.68      0.82      0.74        55
         5.0       0.41      0.49      0.44        57
         6.0       0.70      0.88      0.78        59
         8.0       0.73      0.86      0.79        73
         9.0       0.41      0.37      0.39        59
        10.0       0.89      0.89      0.89        61
        11.0       0.76      0.51      0.61        57
        12.0       0.60      0.43      0.50        65
        13.0       0.58      0.80      0.67        70
        14.0       0.87      0.90      0.89        60
        15.0       0.71      0.46      0.56        70
        16.0       0.67      0.62      0.65        56

    accuracy                           0.68       882
   macro avg       0.68      0.67      0.67       882
weighted avg       0.68      0.68      0.67       882

Confusion Matrix:
 [[50  0  0  3  0 10  2  0  0  1  4  0  0  0]
 [ 0 48  5  1 10  0  0  0  0  2  0  0  0  4]
 [ 0  1 45  1  0  0  0  0  0  0  0  2  0  6]
 [ 3  0  0 28  2  3 10  1  1  2  5  0  2  0]
 [ 0  0  0  1 52  0  3  1  1  0  0  1  0  0]
 [10  0  0  0  0 63  0  0  0  0  0  0  0  0]
 [ 1  0  0 12  2  4 22  3  3  2  6  0  2  2]
 [ 1  0  0  0  0  0  2 54  0  1  3  0  0  0]
 [ 2  1  0  7  0  0  3  1 29  0  8  0  6  0]
 [ 1  3  5  1  7  4  4  0  2 28  4  1  2  3]
 [ 2  1  0  4  0  2  2  0  1  1 56  0  1  0]
 [ 0  0  3  0  0  0  0  0  0  1  0 54  0  2]
 [ 2  3  0 10  0  0  6  0  1  6  9  1 32  0]
 [ 0  3  8  1  1  0  0  1  0  3  1  3  0 35]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.8571428571428571
Classification Report:
               precision    recall  f1-score   support

         1.0       0.88      0.87      0.88        70
         2.0       0.96      0.91      0.93        70
         3.0       0.93      1.00      0.96        55
         5.0       0.49      0.47      0.48        57
         6.0       0.82      0.95      0.88        59
         8.0       0.85      0.97      0.90        73
         9.0       0.63      0.61      0.62        59
        10.0       0.94      0.95      0.94        61
        11.0       0.93      0.67      0.78        57
        12.0       0.90      0.83      0.86        65
        13.0       0.82      0.99      0.90        70
        14.0       0.97      1.00      0.98        60
        15.0       0.95      0.84      0.89        70
        16.0       0.92      0.86      0.89        56

    accuracy                           0.86       882
   macro avg       0.86      0.85      0.85       882
weighted avg       0.86      0.86      0.85       882

Confusion Matrix:
 [[61  0  0  2  0  5  1  0  0  1  0  0  0  0]
 [ 0 64  0  0  3  0  0  0  0  0  0  0  0  3]
 [ 0  0 55  0  0  0  0  0  0  0  0  0  0  0]
 [ 4  0  0 27  2  2 10  1  0  2  9  0  0  0]
 [ 0  0  0  3 56  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 71  1  0  0  0  0  0  0  0]
 [ 0  1  0  9  1  3 36  3  1  2  2  0  1  0]
 [ 0  0  0  0  0  1  1 58  1  0  0  0  0  0]
 [ 0  0  0 10  0  2  3  0 38  0  2  0  2  0]
 [ 2  0  0  0  4  0  3  0  1 54  1  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0 69  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 60  0  0]
 [ 0  2  0  4  0  0  2  0  0  0  1  1 59  1]
 [ 0  0  4  0  2  0  0  0  0  1  0  1  0 48]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.7188208616780045
Classification Report:
               precision    recall  f1-score   support

         1.0       0.70      0.77      0.73        70
         2.0       0.80      0.79      0.79        70
         3.0       0.66      0.82      0.73        55
         5.0       0.35      0.23      0.28        57
         6.0       0.75      0.90      0.82        59
         8.0       0.80      0.96      0.88        73
         9.0       0.45      0.42      0.43        59
        10.0       0.83      0.90      0.87        61
        11.0       0.75      0.68      0.72        57
        12.0       0.72      0.65      0.68        65
        13.0       0.75      0.84      0.79        70
        14.0       0.82      0.82      0.82        60
        15.0       0.74      0.60      0.66        70
        16.0       0.73      0.59      0.65        56

    accuracy                           0.72       882
   macro avg       0.70      0.71      0.70       882
weighted avg       0.71      0.72      0.71       882

Confusion Matrix:
 [[54  0  0  1  1  9  1  0  0  1  2  0  1  0]
 [ 0 55  2  1  2  0  1  0  2  1  0  4  2  0]
 [ 0  2 45  1  1  0  0  0  0  1  0  3  0  2]
 [ 8  1  1 13  3  4  6  2  3  4  6  0  4  2]
 [ 0  0  0  1 53  0  1  0  3  0  0  0  1  0]
 [ 2  0  0  1  0 70  0  0  0  0  0  0  0  0]
 [ 3  1  1  9  4  2 25  3  0  3  3  1  3  1]
 [ 0  0  0  0  0  0  3 55  1  2  0  0  0  0]
 [ 4  2  0  2  1  0  4  1 39  0  2  0  1  1]
 [ 3  0  5  0  3  0  2  3  1 42  2  1  1  2]
 [ 1  0  0  2  0  2  3  0  1  1 59  0  0  1]
 [ 0  3  4  0  0  0  0  0  0  0  1 49  1  2]
 [ 2  2  1  5  2  0  9  1  1  1  3  0 42  1]
 [ 0  3  9  1  1  0  1  1  1  2  1  2  1 33]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.7267573696145124
Classification Report:
               precision    recall  f1-score   support

         1.0       0.78      0.74      0.76        70
         2.0       0.72      0.77      0.74        70
         3.0       0.77      0.93      0.84        55
         5.0       0.31      0.28      0.30        57
         6.0       0.83      0.83      0.83        59
         8.0       0.86      0.95      0.90        73
         9.0       0.48      0.49      0.48        59
        10.0       0.93      0.93      0.93        61
        11.0       0.67      0.60      0.63        57
        12.0       0.72      0.63      0.67        65
        13.0       0.72      0.76      0.74        70
        14.0       0.92      0.77      0.84        60
        15.0       0.68      0.74      0.71        70
        16.0       0.72      0.68      0.70        56

    accuracy                           0.73       882
   macro avg       0.72      0.72      0.72       882
weighted avg       0.73      0.73      0.72       882

Confusion Matrix:
 [[52  0  0  2  0  4  1  0  4  1  5  0  1  0]
 [ 0 54  3  0  2  0  0  0  0  3  0  0  3  5]
 [ 0  0 51  0  0  0  0  0  0  0  0  1  0  3]
 [ 4  3  0 16  1  3 13  1  7  1  5  0  3  0]
 [ 0  3  0  3 49  0  1  0  0  1  0  0  0  2]
 [ 2  0  0  0  0 69  1  0  0  1  0  0  0  0]
 [ 3  2  0 10  1  1 29  1  0  4  2  0  6  0]
 [ 0  0  0  2  0  0  1 57  0  0  0  0  0  1]
 [ 0  0  0 11  0  0  3  1 34  1  3  0  4  0]
 [ 3  5  1  0  3  0  6  0  2 41  2  0  2  0]
 [ 3  0  0  4  0  3  2  0  3  1 53  0  1  0]
 [ 0  2  4  0  0  0  0  0  0  1  0 46  4  3]
 [ 0  2  1  3  0  0  4  1  1  0  4  1 52  1]
 [ 0  4  6  0  3  0  0  0  0  2  0  2  1 38]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.2857142857142857
Classification Report:
               precision    recall  f1-score   support

         1.0       0.62      0.40      0.49        70
         2.0       0.17      0.03      0.05        70
         3.0       0.80      0.15      0.25        55
         5.0       0.27      0.14      0.18        57
         6.0       0.27      1.00      0.42        59
         8.0       0.50      0.15      0.23        73
         9.0       0.67      0.07      0.12        59
        10.0       0.76      0.41      0.53        61
        11.0       0.83      0.18      0.29        57
        12.0       0.56      0.14      0.22        65
        13.0       0.16      0.97      0.27        70
        14.0       0.00      0.00      0.00        60
        15.0       1.00      0.01      0.03        70
        16.0       0.42      0.34      0.38        56

    accuracy                           0.29       882
   macro avg       0.50      0.28      0.25       882
weighted avg       0.50      0.29      0.25       882

Confusion Matrix:
 [[28  0  0  2  2  6  0  0  0  1 31  0  0  0]
 [ 0  2  0  1 24  0  0  0  0  0 41  0  0  2]
 [ 0  0  8  1 14  0  0  0  0  0 14  1  0 17]
 [ 4  0  0  8 12  0  0  2  0  3 28  0  0  0]
 [ 0  0  0  0 59  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  2  0 11  0  0  0  1 53  0  0  0]
 [ 1  1  0  4 20  2  4  2  1  0 24  0  0  0]
 [ 3  0  0  0 10  0  1 25  0  0 22  0  0  0]
 [ 1  0  0  2 21  2  0  0 10  0 21  0  0  0]
 [ 0  4  1  1 22  1  1  2  0  9 22  0  0  2]
 [ 2  0  0  0  0  0  0  0  0  0 68  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0 43  0  0  1]
 [ 0  4  0  7  4  0  0  2  1  1 46  0  1  4]
 [ 0  1  1  2 15  0  0  0  0  1 17  0  0 19]]
==================================================
Model: AdaBoost Classifier
Accuracy: 0.21882086167800455
Classification Report:
               precision    recall  f1-score   support

         1.0       1.00      0.44      0.61        70
         2.0       0.41      0.54      0.47        70
         3.0       0.00      0.00      0.00        55
         5.0       0.12      0.88      0.21        57
         6.0       0.24      0.61      0.34        59
         8.0       0.00      0.00      0.00        73
         9.0       0.00      0.00      0.00        59
        10.0       0.00      0.00      0.00        61
        11.0       0.00      0.00      0.00        57
        12.0       0.00      0.00      0.00        65
        13.0       0.00      0.00      0.00        70
        14.0       0.00      0.00      0.00        60
        15.0       0.00      0.00      0.00        70
        16.0       0.21      0.68      0.33        56

    accuracy                           0.22       882
   macro avg       0.14      0.23      0.14       882
weighted avg       0.15      0.22      0.14       882

Confusion Matrix:
 [[31  0  0 39  0  0  0  0  0  0  0  0  0  0]
 [ 0 38  0  0 18  0  0  0  0  0  0  0  0 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 55]
 [ 0  0  0 50  7  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  6 36  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 73  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 43 14  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 53  8  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 44 13  0  0  0  0  0  0  0  0  0]
 [ 0  7  0 23 27  0  0  0  0  0  0  0  0  8]
 [ 0  0  0 51 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 60]
 [ 0 11  0 46 11  0  0  0  0  0  0  0  0  2]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0 38]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.7494331065759637
Classification Report:
               precision    recall  f1-score   support

         1.0       0.83      0.81      0.82        70
         2.0       0.79      0.66      0.72        70
         3.0       0.75      0.93      0.83        55
         5.0       0.43      0.58      0.50        57
         6.0       0.75      0.86      0.80        59
         8.0       0.79      0.99      0.88        73
         9.0       0.58      0.42      0.49        59
        10.0       0.90      0.89      0.89        61
        11.0       0.84      0.65      0.73        57
        12.0       0.76      0.63      0.69        65
        13.0       0.71      0.81      0.76        70
        14.0       0.91      0.98      0.94        60
        15.0       0.75      0.54      0.63        70
        16.0       0.73      0.71      0.72        56

    accuracy                           0.75       882
   macro avg       0.75      0.75      0.74       882
weighted avg       0.75      0.75      0.75       882

Confusion Matrix:
 [[57  0  0  3  0  6  0  0  1  1  1  0  1  0]
 [ 0 46  5  1  6  0  0  0  0  0  0  0  0 12]
 [ 0  2 51  0  0  0  0  0  0  0  0  0  0  2]
 [ 2  0  0 33  3  2  4  1  0  3  7  0  2  0]
 [ 0  1  0  4 51  0  2  0  0  1  0  0  0  0]
 [ 0  0  0  0  0 72  0  0  0  1  0  0  0  0]
 [ 3  2  0  9  2  5 25  4  1  1  4  0  3  0]
 [ 0  0  0  0  0  1  1 54  1  1  1  0  2  0]
 [ 0  0  0  9  0  2  2  0 37  0  5  0  2  0]
 [ 3  2  4  3  4  0  2  0  1 41  2  1  2  0]
 [ 2  1  0  6  0  2  0  0  0  1 57  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 59  0  1]
 [ 2  2  1  8  1  1  7  1  3  2  3  1 38  0]
 [ 0  2  7  0  1  0  0  0  0  2  0  4  0 40]]

Model Selection(Random Forest)

In [43]:
model=RandomForestClassifier()

model.fit(X_train_scaled,y_train)
#prediction on test set
y_pred=model.predict(X_test_scaled)

#calculate metrics
print('Accuracy:',accuracy_score(y_test,y_pred))
print("Report:",classification_report(y_test,y_pred))
print('Confusion Matrix:',confusion_matrix(y_test,y_pred))

Accuracy: 0.8526077097505669
Report:               precision    recall  f1-score   support

         1.0       0.90      0.87      0.88        70
         2.0       0.94      0.90      0.92        70
         3.0       0.89      0.98      0.93        55
         5.0       0.49      0.47      0.48        57
         6.0       0.82      0.93      0.87        59
         8.0       0.85      0.99      0.91        73
         9.0       0.68      0.58      0.62        59
        10.0       0.92      0.97      0.94        61
        11.0       0.85      0.68      0.76        57
        12.0       0.91      0.82      0.86        65
        13.0       0.83      0.97      0.89        70
        14.0       0.97      0.98      0.98        60
        15.0       0.94      0.87      0.90        70
        16.0       0.89      0.84      0.86        56

    accuracy                           0.85       882
   macro avg       0.85      0.85      0.84       882
weighted avg       0.85      0.85      0.85       882

Confusion Matrix: [[61  0  0  1  0  5  1  0  1  0  1  0  0  0]
 [ 0 63  1  0  3  0  0  0  0  0  0  0  0  3]
 [ 0  0 54  0  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0 27  1  2  9  2  3  3  7  0  2  0]
 [ 0  0  0  3 55  0  1  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 72  0  0  0  0  0  0  0  0]
 [ 0  2  0  9  1  5 34  3  0  2  2  0  1  0]
 [ 0  0  0  0  0  0  1 59  1  0  0  0  0  0]
 [ 0  0  0 11  0  1  2  0 39  0  3  0  1  0]
 [ 3  0  1  0  4  0  1  0  2 53  1  0  0  0]
 [ 1  0  0  1  0  0  0  0  0  0 68  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 59  0  1]
 [ 1  1  0  3  1  0  1  0  0  0  0  1 61  1]
 [ 0  1  5  0  2  0  0  0  0  0  0  1  0 47]]

Single input Predictions

In [44]:
model.predict(X_test_scaled[10].reshape(1,-1))[0]

14.0

In [45]:
print("Predicted Label : ",model.predict(X_test_scaled[10].reshape(1,-1)))
print("Actual Label :",y_test.iloc[10])

Predicted Label :  [14.]
Actual Label : 14.0

In [46]:
print("Predicted Label : ",model.predict(X_test_scaled[100].reshape(1,-1)))
print("Actual Label :",y_test.iloc[100])

Predicted Label :  [16.]
Actual Label : 16.0

In [47]:
print("Predicted Label : ",model.predict(X_test_scaled[5].reshape(1,-1)))
print("Actual Label :",y_test.iloc[5])

Predicted Label :  [2.]
Actual Label : 2.0

Saves and Load files

In [48]:
import pickle
# Save the model to a file

pickle.dump(scaler,open('Models/scaler.pkl','wb'))
pickle.dump(model,open('Models/model.pkl','wb'))

In [49]:
#Load the Scaler,Label encoder and Model 
scaler=pickle.load(open("Models/scaler.pkl",'rb'))
model=pickle.load(open("Models/model.pkl",'rb'))

Recommendation System

In [50]:
import numpy as np
class_names=[
     'lawyer','Doctor','Government Officer','Artist','Unknown',
    'Software Engineer','Teacher','Buisness Owner','Scientist',
    'Banker','Writer','Accountant','Designer',
    'Construction Engineer','Game Developer','Stock Investor',
    'Real Estate Developer'
]
def Recommendation_system(
    gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,math_score,
    history_score,physics_score,chemistry_score,biology_score,geography_score,english_score,
    total_score,average_score
):
# Encode the Categorical features 
    gender_encoded =1 if gender.lower()=='female' else 0 
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0
    
# Create a Feature Array
    feature_array=np.array([[gender_encoded,part_time_job_encoded,absence_days,
                             extracurricular_activities_encoded,weekly_self_study_hours,math_score,
                             history_score,physics_score,chemistry_score,biology_score,
                             geography_score,english_score,total_score,average_score]])
    #Scale Features
    scaled_features=scaler.transform(feature_array)
  
  #predict the career 
    probabilities=model.predict_proba(scaled_features)
    
    #get the top five predicted classes along with their Probabilities 
    top_classes_idx=np.argsort(-probabilities[0])[:5]
    top_classes_names_probs=[(class_names[idx],probabilities[0][idx]) for idx in top_classes_idx]
    return top_classes_names_probs

In [53]:
#example Usage 1

final_recommendations=Recommendation_system(
    gender='female',
    part_time_job=False,
    absence_days=2,
    extracurricular_activities=False,
    weekly_self_study_hours=7,
    math_score=65,
    history_score=60,
    physics_score=97,
    chemistry_score=94,
    biology_score=71,
    geography_score=66,
    english_score=81,
    total_score=534,
    average_score=76.285724)


print("Top 5 Career Recommendations:")
print("="*50)
for class_name,probability in final_recommendations:
    print(f" {class_name} with  Probability:{probability}")

Top 5 Career Recommendations:
==================================================
 Unknown with  Probability:0.37
 Construction Engineer with  Probability:0.37
 Banker with  Probability:0.08
 Doctor with  Probability:0.05
 Government Officer with  Probability:0.04

In [54]:
#sklearn in pychar productionn

import sklearn 
print(sklearn.__version__)

1.5.0